# Generated by Django 5.1 on 2024-08-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('EMPLOYEE', 'Employee'), ('CONTRACTOR', 'Contractor'), ('SALES', 'Sales'), ('WAREHOUSE', 'Warehouse'), ('QUALITY_CONTROL', 'QualityControl'), ('ACCOUNTING', 'Accounting'), ('UPPER_MANAGEMENT', 'UpperManagement'), ('BOARD_MEMBER', 'BoardMember')], default='', max_length=50),
        ),
    ]
