# Generated by Django 5.1 on 2024-08-21 13:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('subscribed_date', models.DateField(blank=True, default='', null=True)),
                ('unsubscribed_date', models.DateField(blank=True, default='', null=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
